spring:
  application:
    name: demo-flowable
  datasource:
    url: jdbc:postgresql://49.232.50.211:5432/postgres
    username: postgres
    password: guanjie0123
    driverClassName: org.postgresql.Driver
server:
  port: 9001
flowable:
  async-executor-activate: false
  database-schema-update: true

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.cloud.entity
logging:
  level:
    org:
      flowable:
        task:
          service:
            impl:
              persistence:
                entity: debug
#    java:
#      sql:
#        ResultSet: debug
#        Connection: debug
#        Statement: debug
#        PreparedStatement: debug


