eureka:
  client:
    enabled: true
    fetch-registry: true
    refresh:
      enable: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    expected-client-renewal-interval-seconds: 30
spring:
  datasource:
    url: jdbc:postgresql://49.232.50.211:5432/postgres
    username: postgres
    password: guanjie0123
    driverClassName: org.postgresql.Driver
    initialization-mode: always
