spring:
  profiles:
    active: dev
  application:
    name: demo-eureka
server:
  port: 8761
---
spring:
  profiles: dev
eureka:
  client:
    enabled: true
    fetch-registry: true
    refresh:
      enable: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    expected-client-renewal-interval-seconds: 30
  datacenter: dev
  environment: dev
